language: python
python:
  - 2.7
  - 3.5
  - 3.6

before_install:
    - pip install -U pip

install:
  - npm install -g grunt-cli
  - npm install
  - pip install -r requirements.txt

script:
  - grunt test

notifications:
  email: false
